import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";

const generateSchema = z.object({
  videoName: z.string().min(1).max(200),
  creator: z.string().max(120).optional().default(""),
  topic: z.string().max(300).optional().default(""),
  language: z.string().max(50).optional().default("English"),
  keywords: z.array(z.string().max(60)).max(30).default([]),
  thumbnailDataUrl: z.string().max(200000).nullable().optional(),
});

function buildMockMetadata(input: z.infer<typeof generateSchema>) {
  const topic = input.topic || input.videoName.replace(/\.[a-z0-9]+$/i, "");
  const kw = input.keywords.filter(Boolean);
  const hashtags = (extra: string[]) =>
    Array.from(
      new Set([...kw, ...extra].map((k) => "#" + k.replace(/[^a-z0-9]+/gi, "").toLowerCase()).filter((h) => h.length > 1)),
    ).slice(0, 12);

  const creatorLine = input.creator ? ` by ${input.creator}` : "";

  return {
    youtube: {
      title: `${topic} — Everything You Need to Know${creatorLine}`.slice(0, 100),
      description:
        `In this video${creatorLine}, we break down ${topic}. ` +
        `We cover the key ideas, practical tips, and takeaways so you can apply them right away.\n\n` +
        `Timestamps:\n00:00 Intro\n00:45 The main idea\n03:20 Practical examples\n06:10 Wrap-up\n\n` +
        `Language: ${input.language}.`,
      hashtags: hashtags(["youtube", "creator", "tutorial"]),
    },
    instagram: {
      caption:
        `${topic} in under 60 seconds${creatorLine}. ` +
        `Save this for later and share it with someone who needs it. ✨`,
      hashtags: hashtags(["reels", "instagram", "viral", "explore"]),
    },
    tiktok: {
      title: `${topic} 🔥`,
      description:
        `Quick ${topic} breakdown${creatorLine}. Follow for more!`,
      hashtags: hashtags(["fyp", "foryou", "tiktok", "viral"]),
    },
  };
}

function buildMockSrt(topic: string, language: string): string {
  const lines = [
    `Welcome — today we're talking about ${topic}.`,
    `This transcript is a demo generated by ClipCaption.`,
    `Language preference: ${language}.`,
    `Let's dive in and cover the essentials.`,
    `Thanks for watching — see you in the next one.`,
  ];
  const pad = (n: number) => n.toString().padStart(2, "0");
  const fmt = (s: number) => `00:${pad(Math.floor(s / 60))}:${pad(s % 60)},000`;
  return lines
    .map((text, i) => {
      const start = i * 4;
      const end = start + 4;
      return `${i + 1}\n${fmt(start)} --> ${fmt(end)}\n${text}\n`;
    })
    .join("\n");
}

export const generateMetadata = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((input) => generateSchema.parse(input))
  .handler(async ({ data, context }) => {
    // Enforce quota + increment atomically.
    const { data: quotaRows, error: quotaErr } = await context.supabase.rpc("record_generation");
    if (quotaErr) throw new Error(quotaErr.message);
    const quota = Array.isArray(quotaRows) ? quotaRows[0] : quotaRows;

    const metadata = buildMockMetadata(data);
    const srt = buildMockSrt(data.topic || data.videoName, data.language);

    const { data: row, error } = await context.supabase
      .from("video_metadata")
      .insert({
        user_id: context.userId,
        video_name: data.videoName,
        thumbnail_url: data.thumbnailDataUrl ?? null,
        language: data.language,
        topic: data.topic,
        keywords: data.keywords,
        metadata_json: metadata,
        subtitle_srt: srt,
      })
      .select("*")
      .single();
    if (error) throw new Error(error.message);

    return { row, quota };
  });

export const listMyMetadata = createServerFn({ method: "GET" })
  .middleware([requireSupabaseAuth])
  .handler(async ({ context }) => {
    const { data, error } = await context.supabase
      .from("video_metadata")
      .select("*")
      .order("created_at", { ascending: false });
    if (error) throw new Error(error.message);
    return data ?? [];
  });

export const deleteMetadata = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((input) => z.object({ id: z.string().uuid() }).parse(input))
  .handler(async ({ data, context }) => {
    const { error } = await context.supabase
      .from("video_metadata")
      .delete()
      .eq("id", data.id)
      .eq("user_id", context.userId);
    if (error) throw new Error(error.message);
    return { ok: true as const };
  });