import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";

const generateSchema = z.object({
  videoName: z.string().min(1).max(200),
  creator: z.string().max(120).optional().default(""),
  topic: z.string().max(300).optional().default(""),
  language: z.string().max(50).optional().default("English"),
  keywords: z.array(z.string().max(60)).max(30).default([]),
  thumbnailDataUrl: z.string().max(200000).nullable().optional(),
  transcript: z.string().max(500000).optional().default(""),
});

function buildMockMetadata(input: z.infer<typeof generateSchema>) {
  const topic = input.topic || input.videoName.replace(/\.[a-z0-9]+$/i, "");
  const kw = input.keywords.filter(Boolean);
  const hashtags = (extra: string[]) =>
    Array.from(
      new Set([...kw, ...extra].map((k) => "#" + k.replace(/[^a-z0-9]+/gi, "").toLowerCase()).filter((h) => h.length > 1)),
    ).slice(0, 12);

  const creatorLine = input.creator ? ` by ${input.creator}` : "";

  return {
    youtube: {
      title: `${topic} — Everything You Need to Know${creatorLine}`.slice(0, 100),
      description:
        `In this video${creatorLine}, we break down ${topic}. ` +
        `We cover the key ideas, practical tips, and takeaways so you can apply them right away.\n\n` +
        `Timestamps:\n00:00 Intro\n00:45 The main idea\n03:20 Practical examples\n06:10 Wrap-up\n\n` +
        `Language: ${input.language}.`,
      hashtags: hashtags(["youtube", "creator", "tutorial"]),
    },
    instagram: {
      caption:
        `${topic} in under 60 seconds${creatorLine}. ` +
        `Save this for later and share it with someone who needs it. ✨`,
      hashtags: hashtags(["reels", "instagram", "viral", "explore"]),
    },
    tiktok: {
      title: `${topic} 🔥`,
      description:
        `Quick ${topic} breakdown${creatorLine}. Follow for more!`,
      hashtags: hashtags(["fyp", "foryou", "tiktok", "viral"]),
    },
  };
}

function transcriptToSrt(transcript: string, language: string): string {
  const clean = transcript.trim();
  if (!clean) return buildMockSrt("your video", language);
  // Split transcript into ~10-word segments, 4s each.
  const words = clean.split(/\s+/);
  const segments: string[] = [];
  for (let i = 0; i < words.length; i += 10) {
    segments.push(words.slice(i, i + 10).join(" "));
  }
  const pad = (n: number) => n.toString().padStart(2, "0");
  const fmt = (s: number) => {
    const h = Math.floor(s / 3600);
    const m = Math.floor((s % 3600) / 60);
    const sec = s % 60;
    return `${pad(h)}:${pad(m)}:${pad(sec)},000`;
  };
  return segments
    .map((text, i) => {
      const start = i * 4;
      const end = start + 4;
      return `${i + 1}\n${fmt(start)} --> ${fmt(end)}\n${text}\n`;
    })
    .join("\n");
}

function buildMockSrt(topic: string, language: string): string {
  const lines = [
    `Welcome — today we're talking about ${topic}.`,
    `This transcript is a demo generated by ClipCaption.`,
    `Language preference: ${language}.`,
    `Let's dive in and cover the essentials.`,
    `Thanks for watching — see you in the next one.`,
  ];
  const pad = (n: number) => n.toString().padStart(2, "0");
  const fmt = (s: number) => `00:${pad(Math.floor(s / 60))}:${pad(s % 60)},000`;
  return lines
    .map((text, i) => {
      const start = i * 4;
      const end = start + 4;
      return `${i + 1}\n${fmt(start)} --> ${fmt(end)}\n${text}\n`;
    })
    .join("\n");
}

async function generateMetadataWithAI(
  input: z.infer<typeof generateSchema>,
): Promise<ReturnType<typeof buildMockMetadata> | null> {
  const key = process.env.LOVABLE_API_KEY;
  if (!key) return null;
  const transcript = input.transcript.trim().slice(0, 12000);
  if (!transcript) return null;

  const system =
    "You generate social media metadata for a video based on its transcript. " +
    "Return STRICT JSON matching the requested schema, no prose. Hashtags are single words prefixed with '#'.";
  const user = `Video name: ${input.videoName}
Creator: ${input.creator || "(unknown)"}
Topic hint: ${input.topic || "(infer from transcript)"}
Language: ${input.language}
User keywords: ${input.keywords.join(", ") || "(none)"}

Transcript:
"""
${transcript}
"""

Return JSON with this exact shape:
{
  "youtube": { "title": string (<=100 chars), "description": string, "hashtags": string[] (<=12) },
  "instagram": { "caption": string, "hashtags": string[] (<=15) },
  "tiktok": { "title": string, "description": string, "hashtags": string[] (<=12) }
}`;

  try {
    const res = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Lovable-API-Key": key,
      },
      body: JSON.stringify({
        model: "openai/gpt-5-mini",
        messages: [
          { role: "system", content: system },
          { role: "user", content: user },
        ],
        response_format: { type: "json_object" },
      }),
    });
    if (!res.ok) return null;
    const json = (await res.json()) as { choices?: Array<{ message?: { content?: string } }> };
    const content = json.choices?.[0]?.message?.content;
    if (!content) return null;
    const parsed = JSON.parse(content);
    return parsed;
  } catch {
    return null;
  }
}

export const generateMetadata = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((input) => generateSchema.parse(input))
  .handler(async ({ data, context }) => {
    // Enforce quota + increment atomically.
    const { data: quotaRows, error: quotaErr } = await context.supabase.rpc("record_generation");
    if (quotaErr) throw new Error(quotaErr.message);
    const quota = Array.isArray(quotaRows) ? quotaRows[0] : quotaRows;

    const aiMetadata = await generateMetadataWithAI(data);
    const metadata = aiMetadata ?? buildMockMetadata(data);
    const srt = data.transcript
      ? transcriptToSrt(data.transcript, data.language)
      : buildMockSrt(data.topic || data.videoName, data.language);

    const { data: row, error } = await context.supabase
      .from("video_metadata")
      .insert({
        user_id: context.userId,
        video_name: data.videoName,
        thumbnail_url: data.thumbnailDataUrl ?? null,
        language: data.language,
        topic: data.topic,
        keywords: data.keywords,
        metadata_json: metadata,
        subtitle_srt: srt,
        transcript: data.transcript || null,
        status: "completed",
      })
      .select("*")
      .single();
    if (error) throw new Error(error.message);

    return { row, quota };
  });

export const listMyMetadata = createServerFn({ method: "GET" })
  .middleware([requireSupabaseAuth])
  .handler(async ({ context }) => {
    const { data, error } = await context.supabase
      .from("video_metadata")
      .select("*")
      .order("created_at", { ascending: false });
    if (error) throw new Error(error.message);
    return data ?? [];
  });

export const deleteMetadata = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((input) => z.object({ id: z.string().uuid() }).parse(input))
  .handler(async ({ data, context }) => {
    const { error } = await context.supabase
      .from("video_metadata")
      .delete()
      .eq("id", data.id)
      .eq("user_id", context.userId);
    if (error) throw new Error(error.message);
    return { ok: true as const };
  });